"""ETL for Yelp business and review enrichment.

Default behavior:
- first try ``data/raw/yelp_reviews_fusion.csv`` (generated by Fusion fetch script)
- fallback to ``YELP_DATA_PATH`` env var when default file is missing

The module also keeps a small Yelp Fusion business collector for refreshing
Manhattan halal restaurant business metadata when ``YELP_API_KEY`` is set.
"""

from __future__ import annotations

import logging
import os
import time
from pathlib import Path

import pandas as pd
import requests

from .base import DatasetSpec, build_empty_frame

logger = logging.getLogger(__name__)
_DEFAULT_FUSION_REVIEW_PATH = Path("data/raw/yelp_reviews_fusion.csv")
_DEFAULT_FUSION_BUSINESS_PATH = Path("data/raw/yelp_business.csv")

API_URL = "https://api.yelp.com/v3/businesses/search"
OUTPUT_PATH = "data/raw/yelp_business.csv"
SNAPSHOT_PATH_TEMPLATE = "data/raw/yelp_business_{date}.csv"
REQUEST_SLEEP_SECONDS = 0.8

SEARCH_TERMS = ["halal"]
OFFSETS = [0, 50, 100, 150]


def _env_float(name: str, default: float) -> float:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        return float(raw)
    except ValueError:
        return default


def _env_int(name: str, default: int) -> int:
    raw = os.environ.get(name, "").strip()
    if not raw:
        return default
    try:
        return int(raw)
    except ValueError:
        return default


GRID_CONFIG = {
    # NYC-wide default bbox (all five boroughs).
    "min_lat": _env_float("YELP_MIN_LAT", 40.49),
    "max_lat": _env_float("YELP_MAX_LAT", 40.92),
    "min_lng": _env_float("YELP_MIN_LNG", -74.26),
    "max_lng": _env_float("YELP_MAX_LNG", -73.70),
    # Slightly coarser default grid to keep API volume manageable.
    "lat_step": _env_float("YELP_LAT_STEP", 0.03),
    "lng_step": _env_float("YELP_LNG_STEP", 0.03),
    "radius": _env_int("YELP_RADIUS_METERS", 1200),
}

DATASET_SPEC = DatasetSpec(
    name="yelp",
    owner="data",
    spatial_unit="restaurant",
    time_grain="date",
    description=(
        "Review text and business metadata for enrichment only after coverage audit."
    ),
    columns=("review_date", "business_id", "restaurant_id", "rating", "review_text"),
)


def run_placeholder_etl() -> pd.DataFrame:
    return build_empty_frame(DATASET_SPEC)


def _load_local() -> pd.DataFrame:
    """Load Yelp reviews from default Fusion CSV or env-configured local file."""
    if _DEFAULT_FUSION_REVIEW_PATH.is_file():
        path = _DEFAULT_FUSION_REVIEW_PATH
        logger.info("etl_yelp: loading default Fusion review file %s", path)
    else:
        path_str = os.environ.get("YELP_DATA_PATH", "")
        if not path_str:
            raise RuntimeError(
                "etl_yelp: missing Yelp input file. Expected default "
                f"{_DEFAULT_FUSION_REVIEW_PATH} or YELP_DATA_PATH env var."
            )
        path = Path(path_str)
        if not path.is_file():
            raise FileNotFoundError(f"etl_yelp: YELP_DATA_PATH={path} does not exist")
        logger.info("etl_yelp: loading from YELP_DATA_PATH %s", path)

    logger.info("etl_yelp: loading from local file %s", path)
    if path.suffix.lower() == ".json":
        return pd.read_json(path, lines=True)
    return pd.read_csv(path)


def _load_business() -> pd.DataFrame:
    """Load Yelp business lat/lon from default business CSV.

    Returns a DataFrame with (id, latitude, longitude) or empty if file missing.
    """
    if not _DEFAULT_FUSION_BUSINESS_PATH.is_file():
        logger.warning(
            "etl_yelp: business file not found at %s — skipping geo join",
            _DEFAULT_FUSION_BUSINESS_PATH,
        )
        return pd.DataFrame(columns=["id", "latitude", "longitude"])
    try:
        df = pd.read_csv(
            _DEFAULT_FUSION_BUSINESS_PATH, usecols=["id", "latitude", "longitude"]
        )
        df["latitude"] = pd.to_numeric(df["latitude"], errors="coerce")
        df["longitude"] = pd.to_numeric(df["longitude"], errors="coerce")
        return df.dropna(subset=["latitude", "longitude"])
    except Exception as exc:
        logger.warning("etl_yelp: could not load business file: %s", exc)
        return pd.DataFrame(columns=["id", "latitude", "longitude"])


def run_etl(limit: int = 50000) -> pd.DataFrame:  # noqa: ARG001
    """Load real Yelp data from local file and enrich with business lat/lon."""
    reviews = _load_local()
    business = _load_business()

    if not business.empty and "business_id" in reviews.columns:
        reviews = reviews.merge(
            business.rename(columns={"id": "business_id"}),
            on="business_id",
            how="left",
        )

    return reviews


def _build_anchor_points() -> list[dict[str, float | str]]:
    anchors: list[dict[str, float | str]] = []
    lat = GRID_CONFIG["min_lat"]
    row = 0
    while lat <= GRID_CONFIG["max_lat"] + 1e-9:
        lng = GRID_CONFIG["min_lng"]
        col = 0
        while lng <= GRID_CONFIG["max_lng"] + 1e-9:
            anchors.append(
                {
                    "anchor_name": f"grid_r{row:02d}_c{col:02d}",
                    "latitude": round(lat, 6),
                    "longitude": round(lng, 6),
                }
            )
            lng += GRID_CONFIG["lng_step"]
            col += 1
        lat += GRID_CONFIG["lat_step"]
        row += 1
    return anchors


ANCHOR_POINTS = _build_anchor_points()
MAX_ANCHORS = _env_int("YELP_MAX_ANCHORS", 0)


def _build_headers(api_key: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {api_key}"}


def _build_params(
    anchor: dict[str, float | str], search_term: str, offset: int
) -> dict[str, float | int | str]:
    return {
        "term": search_term,
        "categories": "restaurants",
        "latitude": anchor["latitude"],
        "longitude": anchor["longitude"],
        "radius": GRID_CONFIG["radius"],
        "limit": 50,
        "offset": offset,
    }


def _extract_businesses(
    businesses: list[dict],
    search_term: str,
    anchor_name: str,
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for business in businesses:
        category_titles = [
            category.get("title", "") for category in business.get("categories", [])
        ]
        coordinates = business.get("coordinates") or {}
        rows.append(
            {
                "id": business.get("id"),
                "name": business.get("name"),
                "categories": ", ".join(title for title in category_titles if title),
                "rating": business.get("rating"),
                "review_count": business.get("review_count"),
                "price": business.get("price"),
                "latitude": coordinates.get("latitude"),
                "longitude": coordinates.get("longitude"),
                "is_closed": business.get("is_closed"),
                "search_term": search_term,
                "anchor_name": anchor_name,
            }
        )
    return rows


def collect_yelp_businesses() -> pd.DataFrame:
    api_key = os.environ.get("YELP_API_KEY", "").strip()
    if not api_key:
        print("Error: YELP_API_KEY environment variable is missing.")
        raise SystemExit(1)

    all_rows: list[dict[str, object]] = []
    headers = _build_headers(api_key)

    anchors = ANCHOR_POINTS[:MAX_ANCHORS] if MAX_ANCHORS > 0 else ANCHOR_POINTS
    for anchor in anchors:
        anchor_name = str(anchor["anchor_name"])
        for search_term in SEARCH_TERMS:
            for offset in OFFSETS:
                params = _build_params(anchor, search_term, offset)
                try:
                    response = requests.get(
                        API_URL, headers=headers, params=params, timeout=30
                    )
                    response.raise_for_status()
                    payload = response.json()
                except requests.RequestException as exc:
                    print(
                        f"Error collecting Yelp data for anchor={anchor_name}, "
                        f"term={search_term}, offset={offset}: {exc}"
                    )
                    break

                businesses = payload.get("businesses", [])
                if not businesses:
                    print(
                        f"No more results for anchor={anchor_name}, "
                        f"term={search_term}, offset={offset}. Stopping query."
                    )
                    break

                all_rows.extend(
                    _extract_businesses(businesses, search_term, anchor_name)
                )
                time.sleep(REQUEST_SLEEP_SECONDS)

    frame = pd.DataFrame(all_rows)
    if "id" in frame.columns:
        frame = frame.drop_duplicates(subset=["id"]).reset_index(drop=True)

    output_dir = os.path.dirname(OUTPUT_PATH)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    snapshot_path = SNAPSHOT_PATH_TEMPLATE.format(date=time.strftime("%Y-%m-%d"))
    frame.to_csv(OUTPUT_PATH, index=False)
    frame.to_csv(snapshot_path, index=False)

    print(f"total rows collected: {len(all_rows)}")
    print(f"unique businesses: {len(frame)}")
    print(f"grid points used: {len(anchors)}")
    print(f"column names: {list(frame.columns)}")
    print(f"saved latest file: {OUTPUT_PATH}")
    print(f"saved snapshot file: {snapshot_path}")
    print("first 5 rows:")
    print(frame.head())

    return frame


if __name__ == "__main__":
    collect_yelp_businesses()
